In [5]:
import numpy as ny
arr1=ny.array(["L","I","K","A",True])
print(arr1)

['L' 'I' 'K' 'A' 'True']


In [2]:
import numpy as ny
arr2=ny.array([5,4,True])
print(arr2)
arr3=ny.array([5,4,False])
print(arr3)

[5 4 1]
[5 4 0]


In [10]:
d1=ny.array([[3,3],[3,2]])
d1.ndim

2

In [12]:
d1.shape

(2, 2)

In [14]:
d1.size

4

In [17]:
d1.dtype

dtype('int32')

In [27]:
a=(ny.arange(1,51,1)**2)
a[a%3==0]

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304], dtype=int32)

In [5]:
ar1=ny.random.randint(0,9,(4,5))
ar2=ar1.mean(axis=1)
ar2[ar2>5.0]

array([6.2, 6.2])

In [4]:
A=ny.array([[n+m*3 for n in range(4)]for m in range(5)])
A

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 9, 10, 11, 12],
       [12, 13, 14, 15]])