Python Review
===

This is a module about python programming for data science. In this module we will teach you tools and techniques for effective data manipulation. This is an essential module as it forms the basis for all upcoming modules. At the end of this module we expect you to be able apply standard data engineering techniques to practical datasets.

[Python](http://python.org) is developed under an open source license, making it freely usable and distributable, even for commercial use. Python's license is administered by the Python Software Foundation. [Guido Van Rossum](https://en.wikipedia.org/wiki/Guido_van_Rossum)  started python as a hobby project and later turned to a general purpose programming language. 

Python is easy to build sharable packages(libraries) and has excellent cross platform support. There are two major verisons of python programming language, 2 and 3. The latest stable version at the time of writing this module is 2.7.12 and 3.6.1. We are using python 3 in this course.

The interface you are seeing is called [jupyter notebook (ipython notebook)](http://jupyter.org) and we will use this in whole of our course as programming environment. Jupyter makes programming more interactive, documentable and fun. 

### Python Programming Files

* Python code is usually stored in text files with the file ending "`.py`":

        my_python_program.py

* Python is and interpreted language and every line in a Python program file is considered to be a Python statement, or part thereof. 

    * The only exception is comment lines, which start with the character `#` or `'''` or `"""`
    
* Python is an indented language. Every code block is described by its indentation

* To run our Python program from the command line we use:

        $ python my_python_program.py

#### Jupyter Notebook

This file - a jupyter notebook -  does not follow the standard pattern with Python code in a text file. Instead, an jupyter notebook is stored as a file in the [JSON](http://en.wikipedia.org/wiki/JSON) format. The advantage is that we can mix formatted text, Python code and code output. It requires the jupyter notebook server to run it though, and therefore isn't a stand-alone Python program as described above. Other than that, there is no difference between the Python code that goes into a program file or an jupyter notebook.

More Information on [jupyter notebook](http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/what_is_jupyter.html)

Its important to know some minimal shortcuts in jupyter notebook, so that you could save some time. They are:

"a"             - inserts a cell above.

"b"             - inserts a cell below. 

"dd"            - deletes the current cell.

"shift + enter" - runs the current cell and selects below.

"ctrl + enter"  - runs the selected cells.

"alt + enter"   - runs the current cell and inserts below.

### Hello, World

Printing to console

In [1]:
%%file greet.py
print("Hello, World!")

Overwriting greet.py


In [2]:
!python greet.py

Hello, World!


### Data Types and Variables

Python variable names can contain alphanumerical characters [__a-z, A-Z, 0-9__] and some special characters ( _ ). 

By convention, variable names start with a lower-case letter, and Class names start with a capital letter.

In addition, there are the keywords that cannot be used as variable names:

```
and as assert break class continue def del elif else except exec finally for from 
global if import in is lambda not or pass print raise return try while with yield
```


__Assignment__

The assignment operator in Python is =. Python is a dynamically typed language, so we do not need to specify the type of a variable when we create one.

In [1]:
# Defining a variable is by value assignment
my_variable = 1.0
print(my_variable)

1.0


In [75]:
a = 10
b = 20

# Variable assignment
c=a+b

__Fundamental Types__

* `int` – represent integers, example: `5`
* `float` – represent real numbers, example: `3.27`
* `bool` – represent Boolean values `True` and `False` 
* `complex` – represent complex numbers example: `11 - 2.2j`
* `str` – represent string of charactors. example: `"abcdef"`
* `NoneType` – special and has one value, `None`
* `type()` can be used to see the type of an object


In [2]:
a = 10
type(a)

int

In [22]:
type(2.7)

float

In [30]:
type(1-2j)

complex

In [23]:
type("a")

str

In [24]:
type(True)

bool

In [25]:
type(None)

NoneType

*Although not explicitly specified, a variable does have a type associated with it. 
The type is derived from the value that was assigned to it.*

In [21]:
type(my_variable)

float

In [108]:
my_variable="abc"
type(my_variable)

str

__Type casting__

At most of the times, depending on your code you need to convert variables and its explained in the following section.
Following are the commands used to convert the variables to `int, float, string, boolean and complex` respectively.

1. `int()` 
2. `float()`
3. `str()`
4. `bool()`
5. `complex()`

In [88]:
x = 1.5 # float
print(x, type(x))

1.5 <class 'float'>


In [89]:
x = int(x) # casting float to int
print(x, type(x))

1 <class 'int'>


In [84]:
z = complex(x)
print(z, type(z))

(1+0j) <class 'complex'>


*Complex variables cannot be cast to floats or integers. We need to use `z.real` or `z.imag` to extract the part of the complex number we want.*

In [85]:
x = float(z)

TypeError: can't convert complex to float

In [87]:
x = float(z.real)
print(x, type(x))

1.0 <class 'float'>


In [90]:
x = float("12")
print(x, type(x))

12.0 <class 'float'>


In [91]:
x = float("12a")
print(x, type(x))

ValueError: could not convert string to float: '12a'

__Operators__

Most operators and comparisons in Python work as one would expect:

__Arithmetic operators__

- **`+`**
- **`-`**
- **`*`**
- **`/`** 
- **`//`** (integer division)
- `**`  (power)



In [95]:
# add, sub, mul, div, power 
1 + 2, 1 - 2, 1 * 2, 1 / 2, 2**10

(3, -1, 2, 0.5, 1024)

Integer division, Modulus

In [98]:
3//2, 13%10

(1, 3)

In [100]:
type(1/2)

float

__Comparison Operators__

- equals: 	**`==`**
- not equals: 	**`!=`**
- greater/less than:	 **`> `** and **` <`**
- greater/less than or equal: 	**`>=`** and **`<=`**

__Logical Operators__
 
- **`and`**
- **`or`**
- **`not`**





In [101]:
True, False

(True, False)

In [102]:
2 > 1, 2 <= 1

(True, False)

In [5]:
1 == 1.0

True

In [106]:
# and
True and False, True & False

(False, False)

In [108]:
# or
True or False, True | False

(True, True)

In [112]:
# not
not True

False

In [31]:
x = int(True)
print(x, type(x))

y = float(False)
print(y, type(y))

1 <class 'int'>
0.0 <class 'float'>


In [118]:
True + True, True * False

(2, 0)

In [127]:
# objects identical?
l1 = l2 = [1,2]
l1 is l2

True

### Data Structures

#### String

Strings are the variable type that is used for storing sequences of characters (Text).

In [26]:
s = "Hello, world!"
type(s)

str

In [27]:
# length of the string: the number of characters
len(s)

13

In [28]:
# replace a substring in a string with something else
s2 = s.replace("world", "test")
print(s2)

Hello, test!


We can index a character in a string using []:

In [32]:
s[0]

'H'

We can extract the arbitrary sequences using indexing (using the syntax [start:stop]).

In [36]:
s[7:12]

'world'

Slice every second character from string `s`

In [47]:
s[::2]

'Hlo ol!'

__String formatting examples__

In [49]:
print("str1", "str2", "str3")  # The print statement concatenates strings with a space

str1 str2 str3


In [50]:
print("str1", 1.0, False, -1j)  # The print statements converts all arguments to strings

str1 1.0 False (-0-1j)


In [51]:
print("str1" + "str2" + "str3") # strings added with + are concatenated without space

str1str2str3


In [52]:
print("value = %f" % 1.0)       # we can use C-style string formatting


value = 1.000000


In [55]:
# this formatting creates a string
s2 = "value1 = %.2f. value2 = %d" % (3.1415, 1.5)

print(s2)

value1 = 3.14. value2 = 1


In [56]:
# alternative, more intuitive way of formatting a string 
s3 = 'value1 = {0}, value2 = {1}'.format(3.1415, 1.5)

print(s3)

value1 = 3.1415, value2 = 1.5


#### Tuple

A tuple consists of a number of values separated by commas, for instance:

In [58]:
t = 12345, 54321, 'hello!'
print(t)

(12345, 54321, 'hello!')


In [59]:
t[2]

'hello!'

Tuples are immutable, and usually contain a heterogeneous sequence of elements.

In [61]:
t[2]=2

TypeError: 'tuple' object does not support item assignment

In [130]:
point = (10, 20)

print(point, type(point))

(10, 20) <class 'tuple'>


In [131]:
point = 10, 20

print(point, type(point))

(10, 20) <class 'tuple'>


In [132]:
point[0] = 20

TypeError: 'tuple' object does not support item assignment

#### List

Python knows a number of compound data types, used to group together other values. The most versatile is the list, which can be written as a list of comma-separated values (items) between square brackets. 

* An ordered collection of objects (components).

* List are analogus to array

* A list allows you to gather a variety of (possibly unrelated) objects under one name.

* You can create lists that consists of mixed data types

* You can create a list of `int, float, string, logical` and `complex` data types together in a single list.


In [136]:
x = (1, 2, "a")
x

(1, 2, 'a')

In [40]:
l = [1,2,3,4]

print(type(l))
print(l)

<class 'list'>
[1, 2, 3, 4]


__Indexing__

Indexing starts at 0

In [41]:
#first element
l[0]

1

In [42]:
#last element
l[3]

4

In [43]:
l[-1]

4

__Slicing__

In [45]:
# Complete list
print(l)

# elements from index 1 till 3 (excluding 3)
print(l[1:3])

# Every second element starting from 0th index
print(l[::2])

# Last element
print(l[-1])

# Last 3 element
print(l[-3:])

[1, 2, 3, 4]
[2, 3]
[1, 3]
4
[2, 3, 4]


__List Operations __

In [144]:
# Elements in a list do not all have to be of the same type
l = [1, 'a', 1.0, 1-1j]
print(l)

[1, 'a', 1.0, (1-1j)]


In [146]:
#Python lists can be arbitrarily nested
nested_list = [1, [2, [3, [4, [5]]]]]
print(nested_list)

[1, [2, [3, [4, [5]]]]]


The `range` function

In [148]:
start = 10
stop = 30
step = 2

list(range(start, stop, step))

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [149]:
list(range(-10, 10))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Adding, inserting, modifying, and removing elements from lists

In [150]:
# create a new empty list
l = []

# add an elements using `append`
l.append(1)
l.append(2)
l.append(2)

print(l)

[1, 2, 2]


List comprehensions

In [74]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

#### Set

Python also includes a data type for sets. A set is an unordered collection with no duplicate elements. 

In [2]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}

In [3]:
print(basket)

{'banana', 'orange', 'apple', 'pear'}


In [5]:
'orange' in basket

True

In [6]:
basket.add("kiwi")
print(basket)

{'banana', 'orange', 'apple', 'pear', 'kiwi'}


In [9]:
basket1 = {'apple', 'orange'}
basket2 = {'kiwi', 'banana', 'orange'}

In [10]:
print(basket1 - basket2)

{'apple'}


In [11]:
print(basket2 - basket1)

{'banana', 'kiwi'}


In [12]:
a = set('abracadabra')
a

{'a', 'b', 'c', 'd', 'r'}

Similarly to list comprehensions, set comprehensions are also supported:

In [73]:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

In [75]:
a = [(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]
a

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

#### Dictionary

A dictionary is an unordered set of {**key**: **value**} pairs, with the requirement that the keys are unique. 

A **key** is an unique identifier for the **value** it refers to.

In [76]:
tel = {'jack': 4098, 'sape': 4139}

In [79]:
tel["jack"]

4098

In [77]:
tel['guido'] = 4127

In [78]:
tel

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In [80]:
list(tel.keys())

['sape', 'jack', 'guido']

In [82]:
list(tel)

['sape', 'jack', 'guido']

In [81]:
sorted(tel)

['guido', 'jack', 'sape']

The `dict()` constructor builds dictionaries directly from sequences of key-value pairs:

In [83]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

### Control Structures

As with most imperative languages, there are three main categories of program control flow:

* Branches or Conditional Statements
* Loops

#### Conditional Statements

##### if

In [84]:
a = 10
if a > 1:
    print("a > 1")

a > 1


##### if-else

In [85]:
a = -10
if a > 1:
    print("a > 1")
else:
    print("a <= 1")

a <= 1


##### if-elif

In [86]:
a = 0
if a > 1:
    print("a > 1")
elif a > -1:
    print("1 >= a > -1")

1 >= a > -1


##### if-elif-else

In [1]:
a = -2
if a > 1:
    print("a > 1")
elif a > -1:
    print("1 >= a > -1")
elif a > -3:
    print("-1 >= a > -3")
else:
    print("a <= -3")

-1 >= a > -3


#### Loops

##### while

In [87]:
a = 5
while a > 0:
    print("a =", a)
    a -= 1

a = 5
a = 4
a = 3
a = 2
a = 1


##### while-break

In [88]:
a = 5
while a > 0:
    print("a =", a)
    a -= 1

    if a == 4:
        break

a = 5


##### while-else

In [89]:
a = 5
while a > 0:
    print("a =", a)
    a -= 1
else:
    print("end of while")

a = 5
a = 4
a = 3
a = 2
a = 1
end of while


##### for

In [90]:
data = [0, 1, 2, 3, 4, 5]
for x in data:
    print(x, end=' ')

0 1 2 3 4 5 

##### for-break

In [91]:
data = [0, 1, 2, 3, 4, 5]
for x in data:
    print(x, end=' ')
    if x == 1:
        break

0 1 

##### Iterating dictionary using for

In [14]:
data = {'Bengaluru': 1, 'London': 2}

for x in data:
    print(x)

Bengaluru
London


In [33]:
data = {'tokyo': 1, 'new york': 2}

for key, value in data.items():
    print(key, end=': ')
    print(value)

new york: 2
tokyo: 1


### Iterators

An iterator is any object that can be iterated upon. They are objects which will return data, one element at a time. 

In [44]:
x = iter([3, 7, 1, 23])

In [46]:
next(x)

7

In [47]:
next(x)

1

In [48]:
next(x)

23

### Generators

Generators are functions that are used to create iterable objects

In [70]:
def generate_numbers(start, end):
    while start <= end:
       yield start
       start += 1

In [76]:
nums = generate_numbers(6, 9)

In [77]:
a = list(nums)

In [78]:
print(a)

[6, 7, 8, 9]


### Functions

A function in Python is defined using the keyword def, followed by a function name, a signature within parentheses __()__, and a colon __:__. The following code, with one additional level of indentation, is the function body.

In [18]:
def print_square(x): # defining the function: <name_of_func>(<arguments>)
    """Prints a value""" # description of a function `docstring`
    print(x ** 2) # body of the function

print_square(1) # function call
print_square(2)
print_square(3)

1
4
9


In [24]:
def square(x):
    """ Returns a value"""
    return x ** 2


print(square(1) + square(2))

5


In [27]:
print(print_square(1) + print_square(2))

1
4


TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

In [30]:
val = print_square(1)\

print(val)

1
None


In [31]:

def sum_and_diff(a, b):
    """Returns a tuple"""
    return a+b,  a-b

y, y_prime = sum_and_diff(1, 2)

print(y)
print(y_prime)

3
-1


In [123]:

def n_power(x, n=2):
    """Function with default argument value"""
    return x ** n

y = n_power(10)

print(y)

100


The function name should be meaniningful and should convey its purpose. Optionally, but highly recommended, we can define a so called "docstring", which is a description of the functions purpose and behaivor. The docstring should follow directly after the function definition, before the code in the function body.

In [128]:
def square(x):
    """
    Computes square of the given number x 
    
    Paramerters
    -----------
    x: int or float
        Number whose square is to be calculated
        
    Returns
    -------
    int or float
        Square of a number
    """
    return x**2

In [129]:
help(square)

Help on function square in module __main__:

square(x)
    Computes square of the given number x 
    
    Paramerters
    -----------
    x: int or float
        Number whose square is to be calculated
        
    Returns
    -------
    int or float
        Square of a number



__Anonymous Functions `lambda`__

In [125]:
f = lambda x: x**2 + 1
print(f(10))

101


### Modules

One of the most important concepts in good programming is to reuse code and avoid repetitions.

The idea is to write functions and classes with a well-defined purpose and scope, and reuse these instead of repeating similar code in different part of a program (modular programming). The result is usually that readability and maintainability of a program is greatly improved. What this means in practice is that our programs have fewer bugs, are easier to extend and debug/troubleshoot. 

Python supports modular programming at different levels. Functions and classes are examples of tools for low-level modular programming. Python modules are a higher-level modular programming construct, where we can collect related variables, functions and classes in a module. A python module is defined in a python file (with file-ending `.py`), and it can be made accessible to other Python modules and programs using the `import` statement. 



Here is what python documentation says about modules:

```
If you quit from the Python interpreter and enter it again, the definitions you have made (functions and variables) are lost. Therefore, if you want to write a somewhat longer program, you are better off using a text editor to prepare the input for the interpreter and running it with that file as input instead. This is known as creating a script. As your program gets longer, you may want to split it into several files for easier maintenance. You may also want to use a handy function that you’ve written in several programs without copying its definition into each program.

To support this, Python has a way to put definitions in a file and use them in a script or in an interactive instance of the interpreter. Such a file is called a module; definitions from a module can be imported into other modules or into the main module (the collection of variables that you have access to in a script executed at the top level and in calculator mode).

A module is a file containing Python definitions and statements. The file name is the module name with the suffix .py appended. Within a module, the module’s name (as a string) is available as the value of the global variable __name__.

```


source: [docs.python.org](https://docs.python.org/3/tutorial/modules.htmhttps://docs.python.org/3/tutorial/modules.html)

Consider the following example: the file `mymodule.py` contains simple example implementations of a variable, function and a class:

In [11]:
%%file mymodule.py
"""
Example of a python module. Contains a variable called my_variable,
a function called my_function, and a class called MyClass.
"""

my_variable = 0

def my_function():
    """
    Example function
    """
    return my_variable
    
class MyClass:
    """
    Example class.
    """

    def __init__(self):
        self.variable = my_variable
        
    def set_variable(self, new_value):
        """
        Set self.variable to a new value
        """
        self.variable = new_value
        
    def get_variable(self):
        return self.variable

Writing mymodule.py


We can import the module `mymodule` into our Python program using `import`:

In [13]:
import mymodule

Use `help(module)` to get a summary of what the module provides:

In [15]:
help(mymodule)

Help on module mymodule:

NAME
    mymodule

DESCRIPTION
    Example of a python module. Contains a variable called my_variable,
    a function called my_function, and a class called MyClass.

CLASSES
    builtins.object
        MyClass
    
    class MyClass(builtins.object)
     |  Example class.
     |  
     |  Methods defined here:
     |  
     |  __init__(self)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  get_variable(self)
     |  
     |  set_variable(self, new_value)
     |      Set self.variable to a new value
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)

FUNCTIONS
    my_function()
        Example function

DATA
    my_variable = 0

FILE
    /Users/vikramkalabi/Datalorelabs

In [16]:
mymodule.my_variable

0

In [17]:
mymodule.my_function() 

0

In [18]:
my_class = mymodule.MyClass() 
my_class.set_variable(10)
my_class.get_variable()

10

### Classes and Objects

Classes are the key features of object-oriented programming. A class is a structure for representing an object and the operations that can be performed on the object. 

In Python a class can contain *attributes* (variables) and *methods* (functions).

A class is defined almost like a function, but using the `class` keyword, and the class definition usually contains a number of class method definitions (a function in a class).

* Each class method should have an argument `self` as its first argument. This object is a self-reference.

* Some class method names have special meaning, for example:

    * `__init__`: The name of the method that is invoked when the object is first created.
    * `__str__` : A method that is invoked when a simple string representation of the class is needed, as for example when printed.
    * There are many more, see http://docs.python.org/3/reference/datamodel.html#special-method-names

In [1]:
class Point:
    """ Simple class for representing a point in a Cartesian coordinate system. """
    
    def __init__(self, x, y):
        """ Create a new Point at x, y. """
        self.x = x
        self.y = y
        
    def translate(self, dx, dy):
        """ Translate the point by dx and dy in the x and y direction. """
        self.x += dx
        self.y += dy
        
    def __str__(self):
        return("Point at [%f, %f]" % (self.x, self.y))


In [2]:
help(Point)

Help on class Point in module __main__:

class Point(builtins.object)
 |  Simple class for representing a point in a Cartesian coordinate system.
 |  
 |  Methods defined here:
 |  
 |  __init__(self, x, y)
 |      Create a new Point at x, y.
 |  
 |  __str__(self)
 |      Return str(self).
 |  
 |  translate(self, dx, dy)
 |      Translate the point by dx and dy in the x and y direction.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [3]:
p1 = Point(0, 0) # this will invoke the __init__ method in the Point class

print(p1) 

Point at [0.000000, 0.000000]


In [4]:
p1.x

0

In [102]:
p2 = Point(1, 1)

p1.translate(0.25, 1.5)

print(p1)
print(p2)

Point at [0.250000, 1.500000]
Point at [1.000000, 1.000000]


### Errors and Exceptions

source: [docs.python.org](https://docs.python.org/3/tutorial/errors.html)

#### Syntax Errors

Syntax errors, also known as parsing errors, are perhaps the most common kind of complaint you get while you are still learning Python

In [20]:
while True 
    print('Hello world')

SyntaxError: invalid syntax (<ipython-input-20-759e7281cd36>, line 1)

The parser repeats the offending line and displays a little ‘arrow’ pointing at the earliest point in the line where the error was detected. The error is caused by (or at least detected at) the token preceding the arrow: in the example, the error is detected at the function print(), since a colon (':') is missing before it. File name and line number are printed so you know where to look in case the input came from a script.

#### Exceptions

Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it. Errors detected during execution are called exceptions and are not unconditionally fatal: you will soon learn how to handle them in Python programs. Most exceptions are not handled by programs, however, and result in error messages as shown here:

In [1]:
def this_fails():
    x = 1/0

In [3]:
this_fails()

ZeroDivisionError: division by zero

######  Handling Exceptions

To gracefully catch errors that are generated by functions and class methods, or by the Python interpreter itself, use the try and  except statements

try:
    # normal code goes here
except:
    # code for error handling goes here
    # this code is not executed unless the code
    # above generated an error


In [2]:
try:
    this_fails()
except ZeroDivisionError as err:
    print('Handling run-time error:', err)

Handling run-time error: division by zero


The try statement works as follows.

1. First, the try clause (the statement(s) between the try and except keywords) is executed.
2. If no exception occurs, the except clause is skipped and execution of the try statement is finished.
3. If an exception occurs during execution of the try clause, the rest of the clause is skipped. Then if its type matches the exception named after the except keyword, the except clause is executed, and then execution continues after the try statement.
4. If an exception occurs which does not match the exception named in the except clause, it is passed on to outer try statements; if no handler is found, it is an unhandled exception and execution stops with a message as shown above.



In [9]:
try:
    print("test")
    # generate an error: the variable test is not defined
    print(test)
except Exception as e:
    print("Caught an exception:" + str(e))
    raise e

test
Caught an exception:name 'test' is not defined


NameError: name 'test' is not defined

To generate an exception we can use the `raise` statement, which takes an argument that must be an instance of the class `BaseException` or a class derived from it. 

In [6]:
raise Exception("description of the error")

Exception: description of the error

In [7]:
a = 1
while a<6:
    print(end="\t"*a)
    print(a)
    a+=1

	1
		2
			3
				4
					5


In [24]:
d1 = {"a":80,"A":56}
for v in sorted(d1.items(),reverse=True):
    print(v)

('a', 80)
('A', 56)


In [19]:
sorted(d1.items())

[('A', 56), ('a', 80)]

In [20]:
for i in range(1,4):
    for j in range(i):
        print(chr(64+i),end=" ")
    print()

A 
B B 
C C C 


## Further reading

* http://www.python.org - The official web page of the Python programming language.
* http://www.python.org/dev/peps/pep-0008 - Style guide for Python programming. Highly recommended. 
* http://www.greenteapress.com/thinkpython/ - A free book on Python programming.
* [Python Essential Reference](http://www.amazon.com/Python-Essential-Reference-4th-Edition/dp/0672329786) - A good reference book on Python programming.

Next: [Numpy](NumPy.ipynb)

In [21]:
d1 = {'a':30,'a':10}

In [22]:
d1

{'a': 10}

In [23]:
sorted(d1.keys(),reverse=True)

['a']

In [25]:
s1 = {1,2,1}
s1

{1, 2}

In [28]:
s2 = frozenset(s1)

In [29]:
type(s2)

frozenset

In [30]:
s1.add(4)

In [34]:
name1 = "Aki"
name2 = "Akil"
name3 = "Aki"
print(id(name1),id(name2),id(name3))

93031776 93030208 93031776


In [35]:
l1 = []
set1 = set()
dict1 = {}
t1 = ()
print(type(l1),type(set1),type(dict1),type(t1))

<class 'list'> <class 'set'> <class 'dict'> <class 'tuple'>


In [36]:
import numpy as np

In [51]:
a1 = np.array([ [[1,2],[67,42],[3,67]],[[12,34],[45,67],[89,67]]])

In [52]:
a1

array([[[ 1,  2],
        [67, 42],
        [ 3, 67]],

       [[12, 34],
        [45, 67],
        [89, 67]]])

In [53]:
a1.shape

(2, 3, 2)

In [56]:
e = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [58]:
e[:2,:2]

array([[1, 2],
       [4, 5]])

In [59]:
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
e[:2,::2]

array([[1, 3],
       [4, 6]])

In [62]:
e[2:,:2]

array([[ 7,  8],
       [10, 11]])

In [63]:
e[2:,1:]

array([[ 8,  9],
       [11, 12]])

In [64]:
list1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
f =  np.array(list1)

In [65]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
f[:2,:3:2]

array([[1, 3],
       [5, 7]])

In [69]:
f[:2,:3:1]

array([[1, 2, 3],
       [5, 6, 7]])

In [70]:
f[::3,::3]

array([[ 1,  4],
       [13, 16]])

In [71]:
f[::-3,::-3]

array([[16, 13],
       [ 4,  1]])

In [72]:
ex = np.ones((4,4))
ex

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
ex[1:3,1:3] = 0
ex

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [80]:
x = np.zeros((4,4),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [85]:
num1 = np.zeros((4,4))
num1[1:3,1:3] = 2
num1[::,::3] = 1
num1[::3,::] = 1
num1

array([[1., 1., 1., 1.],
       [1., 2., 2., 1.],
       [1., 2., 2., 1.],
       [1., 1., 1., 1.]])