In [2]:
from numpy import array

In [44]:
import numpy as np

In [6]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [8]:
?np

In [11]:
int("ab")

ValueError: invalid literal for int() with base 10: 'ab'

In [14]:
complex("10+6j")

(10+6j)

In [22]:
a="10"
print (a)
print(type(a))
a=int(a)
print(type(a))

10
<class 'str'>
<class 'int'>


In [26]:
import math

In [29]:
math.cos(5)

0.28366218546322625

In [41]:
string="Hello world"
print(string[0:5:-1])
print(string[6:16])


world


In [43]:
a=10
b=10
if(a==b):
    print(a==b)

True


In [71]:
s=[1,4,6]
for i in range(8):
    print(i)

0
1
2
3
4
5
6
7


In [84]:
dic={'a':12,6:21}
print(dic['a'])

12


In [89]:
bas={'apple','orange','apple'}
bas.add("pear")
print(bas)

{'pear', 'orange', 'apple'}


In [1]:
bas1={"app","org"}
bas2={"kiwi","bana","org"}
print(bas1-bas2)
print(bas2-bas1)

{'app'}
{'bana', 'kiwi'}


In [3]:
type(1/2)

float

In [7]:
1==1.0

True

In [10]:
1==1.5

False

In [16]:
x = float(True)
x

1.0

In [21]:
l1 = l2 = [2,3,4]
print(l1 is l2)
l1 = [1,2,3]
l1 is l2

True


False

In [27]:
l1 = [1,[2,[3,[4,[5]]]]]
l1

[1, [2, [3, [4, [5]]]]]

In [32]:
d1 = dict([('vec',1),('vit',2)])
d1
d1['vcet']=3
d1

{'vec': 1, 'vit': 2, 'vcet': 3}

In [36]:
for k in d1.keys():
    print(key,end=" ")
print()
for v in d1.values():
    print(v,end=" ")
print()
for k,v in d1.items():
    print(k,":",v)


vcet vcet vcet 
1 2 3 
vec : 1
vit : 2
vcet : 3


In [39]:
pow= lambda x,n : x**n
print(pow(2,4))

16


In [42]:
4**1.2

5.278031643091577

In [46]:
arr = np.array([[1,2,3],[4,5,6]])
arr**1.2

array([[1.        , 2.29739671, 3.73719282],
       [5.27803164, 6.89864831, 8.58581449]])

In [52]:
#### m = 1
arr1 = np.array([[n+m*10 for n in range(4)]for m in range(1,3)])
arr1

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [56]:
import pandas as pd
dt = {'Days':["Mon","Tues","Wed"],'Date':[1,2,3],'Month':['Jan','Feb','Mar']}
df = pd.DataFrame(dt,index=['One','Two','Three'])
print(df.loc['One'].values)
print(df.loc[['One']].values)
print(df.iloc[0].values)

['Mon' 1 'Jan']
[['Mon' 1 'Jan']]
['Mon' 1 'Jan']


In [1]:
import numpy as np
arr1 = np.zeros((5,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
arr1[:,:] = 6
arr1[1:4,1:4] = 5
arr1

array([[6., 6., 6., 6., 6.],
       [6., 5., 5., 5., 6.],
       [6., 5., 5., 5., 6.],
       [6., 5., 5., 5., 6.],
       [6., 6., 6., 6., 6.]])